<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>x86</PlatformTarget>
    <AssemblyName>bfd9010_cli</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BFD9010.Scanner\BFD9010.Scanner.csproj" />
    <ProjectReference Include="..\BFD9010.FhirApi\BFD9010.FhirApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
