"""
Values for the calibration sequence.
"""
# logical block address to write data to
CALIBRATION_WRITE_LBA = [0x01, 0x00, 0x00, 0x1A]
CALIBRATION_WRITE_GROUP_NUMBER = 0x00
CALIBRATION_WRITE_TRANSFER_LENGTH = [0x00, 0x02]
CALIBRATION_WRITE_CBW_CDB_LENGTH = 0x0A

CALIBRATION_SEND_DIAGNOSTIC_ALLOCATION_LENGTH = 0x05
CALIBRATION_RECIEVE_DIAGNOSTIC_ALLOCATION_LENGTH = 0x85
DIAGNOSTIC_CBW_CDB_LENGTH = 0x06

# payloads that are written to memory to start calibration
CALIBRATION_WRITE_PAYLOAD = bytes([0x00, 0x00])
CALIBRATION_SEND_DIAGNOSTIC_PAYLOAD = bytes([0x82, 0x00, 0x00, 0x01, 0x00])

CALIBRATION_CONTROL = 0x00