<Project>
  <PropertyGroup>
    <Version>0.2.0</Version>
    <AssemblyVersion>$(version)</AssemblyVersion>
    <AssemblyVersion>$(version)</AssemblyVersion>
    <FileVersion>$(version)</FileVersion>
    <AssemblyInformationalVersion>$(Version)</AssemblyInformationalVersion>
  </PropertyGroup>
</Project>
